services:
  mongodb:
    image: mongo
    container_name: auction_mongodb
    restart: always
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: auctionadmin
      MONGO_INITDB_ROOT_PASSWORD: auctionpass
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local